name: 'Ctsound '
favicon: null
layout_spectrum: 0.61125
typography_spectrum: 0.4283154
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#003D7E'
    - '#325FA2'
    - '#4E5C6E'
    - '#9DBDEA'
  brandStrength: 0.5053763
  lightness: 0.6738351
  saturation: 0.7598566
  rhythmicContrast: 0.6282735
purpose: []
